name = 'Владислав'
surname = 'Шабалин'
date = 2003
print(name, surname, date, sep='_')
a = ''
a = name 
name = surname
surname = a
#или name, surname = surname, name
print(name, surname, date + 60, sep='_')